### ISSUE TITLE
[Bug] Github Action Excavator auto update is not using the right version from checkver

### ISSUE THREAD

**Issue by LazyGeniusMan** [ScoopInstaller/GithubActions#3]
#### Current Behavior

Detected version from checkver is not used in auto update

#### Expected Behavior

Detected version from checkver is used in auto update

#### Additional context/output

For example, `mindforger` detected checkver is 1.53.0[^1] but in auto update the version is 1.1.1[^2], this also happen in other excavator run[^3].

It's also happen in other manifest, for example: `ldplayer`[^4], `kate`[^5], `mqttx`[^6] and many others.

Is this bug? I tried to locally run checkver for `mqttx` and it's updated correctly.

#### Possible Solution

I haven't found yet what's exactly wrong but looks like excavator is using `auto-pr.ps1` maybe there is something wrong there since `checkver.ps1` is working? but some manifest is updated correctly tho.

[^1]: https://github.com/ScoopInstaller/Extras/runs/4681872557?check_suite_focus=true#step:3:249
[^2]: https://github.com/ScoopInstaller/Extras/runs/4681872557?check_suite_focus=true#step:3:251
[^3]: https://github.com/ScoopInstaller/Extras/runs/4682667936?check_suite_focus=true#step:3:267
[^4]: https://github.com/ScoopInstaller/Extras/runs/4681872557?check_suite_focus=true#step:3:257
[^5]: https://github.com/ScoopInstaller/Extras/runs/4681872557?check_suite_focus=true#step:3:263
[^6]: https://github.com/ScoopInstaller/Extras/runs/4681872557?check_suite_focus=true#step:3:273

**Comment by issaclin32** [comment]
> @issaclin32 can you enable issues for the Actions repo?

Done.

**Comment by LazyGeniusMan** [comment]
Might also want to change `vlc-nightly` manifest, iirc it's also use `$version` variable in the checkver script.

**Comment by rashil2000** [comment]
Great, thanks so much for catching this @LazyGeniusMan :)
