### ISSUE TITLE
[bug?] non-existent `url` function?

### ISSUE THREAD

**Issue by shoucandanghehe** [ScoopInstaller/GithubActions#35]
I noticed in the log of the actions for the issue download failed that there is
```
url: The term 'url' is not recognised as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```
I find 👇
https://github.com/ScoopInstaller/GithubActions/blob/97c03431c3ff0d86ab5f6801caac77c286f3b735/src/Action/Issue.psm1#L115
This line of code looks like it's calling a url function, but there's no url function in your code?
What is this? Does it look like this bug has been around for a long time?

**Comment by shoucandanghehe** [comment]
https://github.com/ScoopInstaller/Main/actions/runs/5465803592/jobs/9949785154
https://github.com/ScoopInstaller/Main/actions/runs/4831501626/jobs/8609036975
https://github.com/ScoopInstaller/Extras/actions/runs/5399471016/jobs/9806633206
https://github.com/ScoopInstaller/Extras/actions/runs/5601500981/jobs/10245472758
there are many logs)

**Comment by rashil2000** [comment]
@niheaven any idea which new function this old function has been refactored into?

**Comment by niheaven** [comment]
It's not refactored, but a file load error. I'll check it soon.
