### ISSUE TITLE
excavator fails to find my release

### ISSUE THREAD

**Issue by couleurm** [ScoopInstaller/GithubActions#40]
Hello, 

Upon checking for updates, Excavator fails to find a newer version of my program

https://github.com/couleur-tweak-tips/utils/actions/runs/7986099354/job/21805808412#step:3:422

Is there something I've configured wrong in the manifest or is because I'm not using a standard numerical tag?

https://github.com/couleur-tweak-tips/utils/blob/main/bucket/smoothie.json

**Comment by niheaven** [comment]
The `checkver: "github"` needs special version format, ref: https://github.com/ScoopInstaller/Scoop/wiki/App-Manifest-Autoupdate#special-cases
